In [89]:
!pip install janome
!pip install gensim

In [1]:
import numpy as np
import janome
from janome.tokenizer import Tokenizer
from gensim import corpora, matutils

In [91]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
import pandas as pd
df = pd.read_csv('out_sample.csv')

In [4]:
tokenizer = Tokenizer()
word_list = []
for review in df['レビュー'].values:
    tokens = tokenizer.tokenize(review)
    words = []
    for token in tokens:
        # 単語を標準形に修正
        word = token.base_form
        # 品詞を取得
        part = token.part_of_speech.split(',')[0]
        # ポジネガに関係なさそうな品詞を除外
        if (part!='助詞')and(part!='助動詞')and(part!='記号'):
            words.append(word)
    word_list.append(words)

In [5]:
word_list

[['料理',
  'いい',
  'の',
  '料理',
  '使用',
  'する',
  '固形',
  '燃料',
  '全て',
  'エスビット',
  '製',
  '固形',
  '燃料',
  'ため',
  '本通り',
  'やる',
  '固形',
  '燃料',
  '代',
  'バカ',
  'なる',
  'なかなか',
  '手',
  '入る',
  'にくい',
  'の',
  '難',
  '感じる',
  '100',
  '均',
  '手',
  '入る',
  '固形',
  '燃料',
  '加熱',
  '時間',
  '表記',
  '5'],
 ['固形', '燃料', '消える', 'かき混ぜる', '固形', '燃料', '足す', '点火', '全然', '自動'],
 ['読み物',
  '面白い',
  '実際',
  '作る',
  'みる',
  'うまい',
  'いく',
  'レシピ',
  'ある',
  '本文',
  '中',
  'レシピ',
  '鵜呑み',
  'する',
  'いきなり',
  'キャンプ',
  '本番',
  '少々',
  'リスク',
  '高い',
  'しれる'],
 ['トランギア',
  'メスティン',
  'エスビット',
  'ポケット',
  'ストーブ',
  'あっと言う間に',
  '美味しい',
  'ご飯',
  '炊ける',
  'こと',
  '感動',
  'する',
  'レシピ',
  '本',
  '購入',
  'する',
  'みる',
  '材料',
  '揃える',
  'おく',
  'メスティン',
  'ぶち込む',
  'ポケット',
  'ストーブ',
  '乗っける',
  '固形',
  '燃料',
  '火',
  'つける',
  '後',
  'ほったらかす',
  '美味しい',
  '映える',
  '料理',
  '出来上がる',
  'この',
  'レシピ',
  '本',
  'メニュー',
  '全部',
  'クリア',
  'する',
  '言う',
  '楽しみ',
  '逃れる',
  'られる',
  'そう'],
 ['記事', 'レシピ', 'うち', '2

In [6]:
# 分かち書きした文書から辞書を作る
dictionary = corpora.Dictionary(word_list)

# 辞書の確認
dictionary.token2id

{'!': 251,
 '%': 596,
 '(': 102,
 ')': 103,
 '+++++++': 252,
 '.': 447,
 '1': 448,
 '10': 597,
 '100': 0,
 '1100': 633,
 '1300': 175,
 '2': 85,
 '3000': 634,
 '4': 137,
 '5': 1,
 '7': 759,
 '8': 547,
 '9': 449,
 '99': 628,
 'A': 253,
 'Delivery': 254,
 'Fast': 255,
 'Kindle': 719,
 'YouTube': 366,
 'm': 666,
 'あっと言う間に': 53,
 'あと': 598,
 'あの世': 256,
 'あふれる': 800,
 'ある': 34,
 'ある程度': 525,
 'いい': 2,
 'いう': 450,
 'いきなり': 35,
 'いきる': 138,
 'いく': 36,
 'いける': 399,
 'いざ': 569,
 'いただく': 235,
 'いっか': 667,
 'いつか': 139,
 'いまいち': 140,
 'いや': 257,
 'いる': 104,
 'うち': 86,
 'うまい': 37,
 'え': 105,
 'お': 229,
 'おく': 54,
 'おすすめ': 720,
 'おっぱい': 258,
 'おもしろい': 430,
 'おる': 236,
 'お互い': 367,
 'お茶漬け': 106,
 'かかる': 237,
 'かき混ぜる': 28,
 'かく': 451,
 'かける': 760,
 'かつ': 87,
 'かなう': 668,
 'かなり': 368,
 'かぶる': 635,
 'が': 369,
 'きちんと': 610,
 'きっと': 721,
 'く': 431,
 'くる': 400,
 'くれる': 198,
 'こういう': 611,
 'こと': 55,
 'この': 56,
 'これ': 107,
 'これから': 401,
 'こんな': 259,
 'ご': 260,
 'ごく': 500,
 'ご飯': 57,
 'さ': 501,
 'さまざま': 761,


In [7]:
# 辞書からBoWを作る（ID番号と、登場回数）
#bow_1 = dictionary.doc2bow(word_list[0])
#bow_2 = dictionary.doc2bow(word_list[2])
#bow_3 = dictionary.doc2bow(word_list[2])
#bow_4 = dictionary.doc2bow(word_list[3])
#bow_5 = dictionary.doc2bow(word_list[4])

bows = []
for word in word_list:
    bow = dictionary.doc2bow(word)
    bows.append(bow)

In [18]:
bow[0]

(56, 1)

In [9]:
bow[1]

(58, 1)

In [11]:
# 長さを確認すると、バラバラ
len(bow[0]), len(bow[1]), len(bow[2])

(2, 2, 2)

In [12]:
# 長さを揃える
#bow_1 = matutils.corpus2dense([bow_1], len(dictionary))
#bow_2 = matutils.corpus2dense([bow_2], len(dictionary))
#bow_3 = matutils.corpus2dense([bow_3], len(dictionary))
#bow_4 = matutils.corpus2dense([bow_4], len(dictionary))
#bow_5 = matutils.corpus2dense([bow_5], len(dictionary))
bows2 = []
for bow in bows:
    bows2.append(matutils.corpus2dense([bow], len(dictionary)))

In [20]:
len(bows2[0])

817

In [24]:
len(dictionary)

817

In [25]:
bows2[0]

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [2.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [2.],
       [1.],
       [1.],
       [4.],
       [1.],
       [1.],
       [2.],
       [2.],
       [1.],
       [1.],
       [4.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],

In [26]:
# 長さが揃う
#len(bow_1), len(bow_2), len(bow_3), len(bow_4), len(bow_5)

In [27]:
# ディープラーニングで扱う為に、ベクトルを縦向き ⇒ 横向きに変換する
#bow_1 = bow_1.reshape(len(dictionary))
#bow_2 = bow_2.reshape(len(dictionary))
#bow_3 = bow_3.reshape(len(dictionary))
#bow_4 = bow_4.reshape(len(dictionary))
#bow_5 = bow_5.reshape(len(dictionary))
bows3 = []
for bow in bows2:
    bows3.append(bow.reshape(len(dictionary)))

In [28]:
bows3[0]

array([1., 1., 1., 1., 1., 1., 1., 1., 2., 1., 1., 1., 1., 1., 2., 1., 1.,
       4., 1., 1., 2., 2., 1., 1., 4., 1., 1., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [37]:
# ニューラルネットワークに入力するために、np.array型に集約する
x = np.array(bows3)
print(len(x), len(x[0]))
x

40 817


array([[1., 1., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 1., 1.]], dtype=float32)

In [39]:
# ポジネガのラベルを「0：ネガ、１：ポジ」に変換してnp.array型に集約
pn = list(map(float, df['★の数'].values))
t = []
for i in pn:
    if i >= 3:
        t.append(1)
    else:
        t.append(0)

t = np.array(t)
t

array([1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [40]:
# Kerasをインポート
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import np_utils
from sklearn.model_selection import train_test_split

C:\Users\midni\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [41]:
# 正解ラベルをOne-Hot形式に変換
t = np_utils.to_categorical(t)

# データとTrain, Valに分割
x_train, x_val, t_train, t_val = train_test_split(x, t, train_size=0.7, random_state=0)

In [42]:
# ニューラルネットワークの定義（簡単な３層）
# 難易度を下げるためにSequentialで書きましょう

np.random.seed(0)
model = Sequential()
model.add(Dense(10, input_shape=bows3[0].shape, activation='relu'))
model.add(Dense(2, activation='softmax'))
optimizser = keras.optimizers.Adam()
model.compile(loss='categorical_crossentropy', optimizer=optimizser, metrics=['accuracy'])

Instructions for updating:
Colocations handled automatically by placer.


In [43]:
# 学習の実行
history = model.fit(x_train, t_train,
          batch_size=5,
          epochs=10,
          verbose=1,
          validation_data=(x_val, t_val))

Instructions for updating:
Use tf.cast instead.
Train on 28 samples, validate on 12 samples
Epoch 1/10
28/28 [==============================] - 1s 29ms/step - loss: 1.0521 - acc: 0.1786 - val_loss: 0.9101 - val_acc: 0.0833
Epoch 2/10
28/28 [==============================] - 0s 2ms/step - loss: 0.8629 - acc: 0.2143 - val_loss: 0.8400 - val_acc: 0.1667
Epoch 3/10
28/28 [==============================] - 0s 643us/step - loss: 0.7396 - acc: 0.2857 - val_loss: 0.7947 - val_acc: 0.2500
Epoch 4/10
28/28 [==============================] - 0s 972us/step - loss: 0.6714 - acc: 0.5000 - val_loss: 0.7607 - val_acc: 0.3333
Epoch 5/10
28/28 [==============================] - 0s 1ms/step - loss: 0.6307 - acc: 0.7500 - val_loss: 0.7365 - val_acc: 0.4167
Epoch 6/10
28/28 [==============================] - 0s 768us/step - loss: 0.6039 - acc: 0.7857 - val_loss: 0.7175 - val_acc: 0.4167
Epoch 7/10
28/28 [==============================] - 0s 571us/step - loss: 0.5809 - acc: 0.8929 - val_loss: 0.7024 - val_a

In [44]:
# 予測を実行してみる
results = model.predict(x_val)
results #左が「０：ネガ」の確率、右が「１：ポジ」の確率 ⇒ 確率なので足すと合計１になる

array([[0.46927965, 0.53072035],
       [0.38867816, 0.6113218 ],
       [0.37004045, 0.6299595 ],
       [0.5849972 , 0.41500282],
       [0.5779329 , 0.42206708],
       [0.4938251 , 0.5061749 ],
       [0.5051339 , 0.49486604],
       [0.47872797, 0.521272  ],
       [0.4455992 , 0.5544008 ],
       [0.44385996, 0.55614   ],
       [0.46887323, 0.53112674],
       [0.4826808 , 0.5173192 ]], dtype=float32)

In [45]:
# ポジネガの判定
for result in results:
    result = result.argmax()
    if result == 0:
        print('ネガ')
    else:
        print('ポジ')

ポジ
ポジ
ポジ
ネガ
ネガ
ポジ
ネガ
ポジ
ポジ
ポジ
ポジ
ポジ


In [46]:
t_val

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.]], dtype=float32)